<h1>View Details</h1>

    <?php $data=$block->getFormCollection(); 
    ?> 
    <table>
     <tr>
         <th><strong>Id:</strong></th>
         <th><strong>Name:</strong></th>
         <th><strong>Email:</strong></th>
         <th><strong>Phone no:</strong></th>
         <th><strong>Gender:</strong></th>
         <th><strong>Address:</strong></th>
         <th><strong>Delete</strong></th>
         <th><strong>Edit</strong></th>

     </tr>
     <?php
     foreach($data as $value)
     {
         ?>
         <tr>
         <td><?php echo $value->getId();?></td>
        <td><?php echo $value->getName();?></td>
        <td><?php echo $value->getEmail();?></td>
        <td><?php echo $value->getPhone();?></td>
        <td><?php echo $value->getGender();?></td>
        <td><?php echo $value->getAddress();?></td>
        <td><a href="<?= $this->getUrl('form/index/delete/').'id/'.$value->getId();?>">Delete</a></td>
        <td><a href="<?= $this->getUrl('form/index/index/').'id/'.$value->getId();?>">Edit</a></td>
        </tr>
   
    <?php
     }
     ?>
     </table>